// Importing the createSlice function from the "@reduxjs/toolkit" package
import { createSlice } from "@reduxjs/toolkit";

// Creating a slice of the Redux store for managing UI state
const uiSlice = createSlice({
  name: "ui", // Name of the slice
  initialState: { cartIsVisible: false }, // Initial state of the slice
  reducers: {
    toggle(state) {
      // Reducer function for toggling the cart visibility
      state.cartIsVisible = !state.cartIsVisible;
    },
  },
});

// Exporting the actions generated by the uiSlice
export const uiActions = uiSlice.actions;

// Exporting the uiSlice as the default export
export default uiSlice;
